[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.copy]
dependencies = ["build"]
script = ['''
 cp -rf target/release/tgm ~/.cargo/bin/tgm
''']
